### ISSUE TITLE
physic disk maybe full soon, so reclaim space, -1.0，但是磁盘空间还很多

### ISSUE THREAD

**Issue by 0kai** [apache/rocketmq-externals#282]
我在docker中启动了broker，启动是正常的，但是无法消费
```
namesrv_1_f74cc4c36bbc | OpenJDK 64-Bit Server VM warning: Using the DefNew young collector with the CMS collector is deprecated and will likely be removed in a future release
namesrv_1_f74cc4c36bbc | OpenJDK 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
namesrv_1_f74cc4c36bbc | The Name Server boot success. serializeType=JSON
broker-a_1_34802fb779da | The broker[broker-a, 10.29.46.181:10911] boot success. serializeType=JSON and name server is 10.30.85.202:9876;10.29.46.181:9876
broker-b_1_be9b884f1652 | The broker[broker-b, 10.29.46.181:20911] boot success. serializeType=JSON and name server is 10.30.85.202:9876;10.29.46.181:9876
```

查看store.log，发现报了磁盘空间不足的问题
```
2019-05-13 22:20:45 WARN StoreScheduledThread1 - disk space will be full soon, but delete file failed.
2019-05-13 22:20:55 INFO StoreScheduledThread1 - physic disk maybe full soon, so reclaim space, -1.0
2019-05-13 22:20:55 INFO StoreScheduledThread1 - begin to delete before 48 hours file. timeup: false spacefull: true manualDeleteFileSeveralTimes: 0 cleanAtOnce: false
```

但是服务器的磁盘空间还是很多
```
sh-4.2# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          79G   16G   60G  21% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/vdb         99G   16G   78G  17% /root
/dev/vda1        79G   16G   60G  21% /etc/hosts
shm              64M   36K   64M   1% /dev/shm
tmpfs           7.8G     0  7.8G   0% /sys/firmware
```

问题：不是应该达到75%才有这样的问题吗
而且我发现store/commitlog  consumequeue index等目录并没有创建

**Comment by walking98** [comment]
@0kai 你是如何启动的，相关的配置是什么 ？

**Comment by 0kai** [comment]
@walking98 我是用github里面docker-compose启动的，其中一台服务器

```
version: '3'
services:
  namesrv:
    image: rocketmqinc/rocketmq:4.4.0
    ports:
      - 9876:9876
    volumes:
      - /jiniutech/rocketmq/namesrv:/home/rocketmq
    environment:
      - TZ=Asia/Shanghai
      - MAX_POSSIBLE_HEAP=209715200
    command: sh mqnamesrv

  broker-a:
    image: rocketmqinc/rocketmq:4.4.0
    ports:
      - 10912:10912
      - 10911:10911
      - 10909:10909
    volumes:
      - /jiniutech/rocketmq/broker-a:/home/rocketmq
      - /jiniutech/rocketmq/broker-a-s.conf:/opt/broker.conf
    environment:
      - TZ=Asia/Shanghai
      - MAX_POSSIBLE_HEAP=524288000
      - NAMESRV_ADDR=10.30.85.202:9876;10.29.46.181:9876
    command: sh mqbroker -c /opt/broker.conf

  broker-b:
    image: rocketmqinc/rocketmq:4.4.0
    ports:
      - 20912:20912
      - 20911:20911
      - 20909:20909
    volumes:
      - /jiniutech/rocketmq/broker-b:/home/rocketmq
      - /jiniutech/rocketmq/broker-b.conf:/opt/broker.conf
    environment:
      - TZ=Asia/Shanghai
      - MAX_POSSIBLE_HEAP=524288000
      - NAMESRV_ADDR=10.30.85.202:9876;10.29.46.181:9876
    command: sh mqbroker -c /opt/broker.conf
```

```
brokerClusterName=DefaultCluster
brokerName=broker-b
brokerId=0
deleteWhen=04
fileReservedTime=48
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
autoCreateTopicEnable=true
brokerIP1=10.29.46.181
brokerIP2=10.29.46.181
listenPort=20911
```

```
brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=1
deleteWhen=04
fileReservedTime=48
brokerRole=SLAVE
flushDiskType=ASYNC_FLUSH
autoCreateTopicEnable=true
brokerIP1=10.29.46.181
brokerIP2=10.29.46.181
listenPort=10911
```
